version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: production
            APP_DEBUG: false
            APP_KEY: base64:CRGd0FKtlQ0EGooVcHwQ58FpcEZz4KBZZhkIXeLbUyo=
            DB_CONNECTION: mysql
            DB_HOST: s0i9g.h.filess.io
            DB_PORT: 3307
            DB_DATABASE: truck_supperflag
            DB_USERNAME: truck_supperflag
            DB_PASSWORD: e36c4e20fa2d0662c14ad3238cc5d049cd04e1ba
